<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src\**\*.cs" />
    <None Include="tc-batch-rename.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="tc-batch-rename.json.example" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
